Develop
fogbow/resource-catalog-service pull request #1
Opened 2019-10-31 13:59 UTC by anderson-dantas

2019-10-31 14:18 UTC, ANKerD requested changes

2019-10-31 14:18 UTC, ANKerD commented on src/main/java/cloud/fogbow/rcs/api/http/response/Version.java
> +    @ApiModelProperty(example = "v.2.0.0-rcs-3191466-ras-ec6bf564-as-c803775-common-4e0d74e")
Please, change it to v1.

2019-10-31 14:18 UTC, ANKerD commented on src/main/java/cloud/fogbow/rcs/constants/ConfigurationPropertyKeys.java
> +    public static final String MEMBERSHIP_SERVICE_URL_KEY = "fogbow_membership_service_url";
Can you make this key simple? like 'ms_url'.

2019-10-31 14:18 UTC, ANKerD commented on src/main/java/cloud/fogbow/rcs/core/ApplicationFacade.java
> +	private static final Logger LOGGER = Logger.getLogger(ApplicationFacade.class);
Fix this class identation please.

2019-10-31 14:18 UTC, ANKerD commented on src/main/resources/application-dev.properties
> +server.port=8082
I think this port is already taken by another Fog-service. Please change it to a higher number.

2019-11-21 12:30 UTC, pauloewerton requested changes
@ANKerD can you please check whether this pr is actually valid?

2019-11-22 18:09 UTC, closed without merging